# Generated by Django 4.2.2 on 2023-07-07 05:40

from django.db import migrations
from django.contrib.auth import models as auth_models
from account import enums


def seed_data(apps, schema_editor):
    for group in enums.Group:
        auth_models.Group.objects.get_or_create(name=group.value)


class Migration(migrations.Migration):

    dependencies = [('auth', '__latest__')]

    operations = [
        migrations.RunPython(seed_data),
    ]
